plugins: ["./custom-gcp", "./custom-plugins/custom-plugin", "@tkow/npm-plugin"]
cache: ./.syncenv
setting:
  - type: ".envrc"
    output_dir: ./artifacts
    env:
      BOOLEAN_TEST: true
      NUMBER_TEST: 1
      DOUBLE_QUOTE_TEST: ${DOUBLE_QUOTE_TEST}
      NOT_REPLACED: NOT_REPLACED
      REPLACED: ${TO_BE_REPLACE}
      PLUGIN_TEST: ${PLUGIN_TEST}
      PLUGIN_NPM_TEST: $PLUGIN_NPM_TEST
    replaces:
      DOUBLE_QUOTE_TEST: 'double "quote test'
      TO_BE_REPLACE: replaceId
      PLUGIN_TEST: "__custom:test__"
      PLUGIN_NPM_TEST: "__npm:test__"
    pipes:
      PLUGIN_TEST: "postfix(1)"
      PLUGIN_NPM_TEST: "npm-postfix"
  - type: ".env"
    output_dir: ./artifacts
    filename: .env.dev
    quote: "'"
    env:
      BOOLEAN_TEST: ${BOOLEAN_TEST}
      NUMBER_TEST: ${NUMBER_TEST}
      ENV_REPLACER_TEST: __default:foo__
      QUOTE_TEST: $QUOTE_TEST
      ESCAPE_TEST: $ESCAPE_TEST
      PIPE_TEST: $PIPE_TEST
      PIPE_REGEXP_TEST: $PIPE_REGEXP_TEST
      PIPE_MULTIPLE_TEST: $PIPE_MULTIPLE_TEST
      NOT_REPLACED: NOT_REPLACED
      REPLACED: ${TO_BE_REPLACE}
      REPLACED_PROVIDER: $TO_BE_REPLACE_PROVIDER
    replaces:
      BOOLEAN_TEST: false
      NUMBER_TEST: 0
      QUOTE_TEST: "single 'quote test"
      ESCAPE_TEST: "\n\t\r'\"@$#-_=*&^\\%~`"
      PIPE_TEST: "PIPE_FAILED"
      PIPE_REGEXP_TEST: "PIPE_FAILED"
      PIPE_MULTIPLE_TEST: PIPE_FAILED
      TO_BE_REPLACE: replaceId
      TO_BE_REPLACE_PROVIDER: __gcp:replaceId__
    pipes:
      PIPE_TEST: "replace(FAILED, SUCCESS)"
      PIPE_REGEXP_TEST: 'replace(FAILED, *UCCE**) | replace(/\*/g, S)'
      PIPE_MULTIPLE_TEST: ['replace(FAILED, "SUCCESS ")', trim]
    default_replacer: default
  - type: file
    output_path: ./artifacts/file-output.txt
    placeholder: $TO_BE_REPLACE $TO_BE_REPLACE_PROVIDER
    replaces:
      TO_BE_REPLACE: replaceId
      TO_BE_REPLACE_PROVIDER: __gcp:replaceId__
    default_replacer?: default
  - type: template
    input_path: ./.env.template
    output_path: ./artifacts/template-output.env
    replaces:
      TO_BE_REPLACE: replaceId
      TO_BE_REPLACE_PROVIDER: __gcp:replaceId__
    default_replacer?: default
